kind: pipeline
name: docker

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: 8.0-octane-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.dev
      tags: 8.0-octane-dev
      build_args:
        - php_version=8.0
    depends_on: [ fetch-tags ]

  - name: 8.0-octane-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.prod
      tags: 8.0-octane-prod
      build_args:
        - php_version=8.0
    depends_on: [ fetch-tags ]

  - name: 8.1-octane-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.dev
      tags: 8.1-octane-dev
      build_args:
        - php_version=8.1
    depends_on: [ fetch-tags ]

  - name: 8.1-octane-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.prod
      tags: 8.1-octane-prod
      build_args:
        - php_version=8.1
    depends_on: [ fetch-tags ]

  - name: 8.0-apache-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.dev
      tags: 8.0-apache-dev
      build_args:
        - php_version=8.0
    depends_on: [ fetch-tags ]

  - name: 8.0-apache-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.prod
      tags: 8.0-apache-prod
      build_args:
        - php_version=8.0
    depends_on: [ fetch-tags ]

  - name: 8.1-apache-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.dev
      tags: 8.1-apache-dev
      build_args:
        - php_version=8.1
    depends_on: [ fetch-tags ]

  - name: 8.1-apache-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.prod
      tags: 8.1-apache-prod
      build_args:
        - php_version=8.1
    depends_on: [ fetch-tags ]

