kind: pipeline
name: docker

trigger:
  ref:
    - refs/heads/main
    - "refs/tags/**"

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: 8.2-apache-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.dev
      tags: 8.2-apache-dev
      build_args:
        - php_version=8.2
    depends_on: [ fetch-tags ]

  - name: 8.2-apache-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.prod
      tags: 8.2-apache-prod
      build_args:
        - php_version=8.2
    depends_on: [ fetch-tags ]

  - name: 8.2-octane-frankenphp-base
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.base
      tags: 8.2-octane-frankenphp-base
      build_args:
        - php_base_image=dunglas/frankenphp:php8.2-bookworm
    depends_on: [ fetch-tags ]

  - name: 8.2-octane-frankenphp
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.frankenphp
      tags: 8.2-octane-frankenphp
      build_args:
        - php_base_image=kolaente/laravel:8.2-octane-frankenphp-base
    depends_on: [ 8.2-octane-frankenphp-base ]

  - name: 8.3-apache-dev
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.dev
      tags: 8.3-apache-dev
      build_args:
        - php_version=8.3
    depends_on: [ fetch-tags ]

  - name: 8.3-apache-prod
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./apache/
      dockerfile: ./apache/Dockerfile.prod
      tags: 8.3-apache-prod
      build_args:
        - php_version=8.3
    depends_on: [ fetch-tags ]

  - name: 8.3-octane-frankenphp-base
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.base
      tags: 8.3-octane-frankenphp-base
      build_args:
        - php_base_image=dunglas/frankenphp:php8.3-bookworm
    depends_on: [ fetch-tags ]

  - name: 8.3-octane-frankenphp
    image: plugins/docker:linux-amd64
    pull: true
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kolaente/laravel
      context: ./octane/
      dockerfile: ./octane/Dockerfile.frankenphp
      tags: 8.3-octane-frankenphp
      build_args:
        - php_base_image=kolaente/laravel:8.3-octane-frankenphp-base
    depends_on: [ 8.3-octane-frankenphp-base ]
