ARG php_base_image
FROM ${php_base_image}

RUN apt-get install -y mariadb-client && \
  docker-php-ext-install mysqli curl exif && \
  docker-php-ext-install pdo pdo_mysql

RUN pecl install swoole && docker-php-ext-enable swoole

# The octance watcher requires node
ENV NODE_MAJOR=20
RUN apt-get update && \
   apt-get install -y ca-certificates curl gnupg && \
   mkdir -p /etc/apt/keyrings && \
   curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg && \
   echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list && \
   apt-get update && apt-get install nodejs -y

WORKDIR /var/www

ADD setup.sh /usr/local/bin/setup
ADD run-dev.sh /run.sh
