ARG php_version
FROM php:${php_version}-bullseye

RUN echo "upload_max_filesize = 2G; " > /usr/local/etc/php/conf.d/upload.ini && \
echo "post_max_size = 2500M;" >> /usr/local/etc/php/conf.d/upload.ini && \
echo "date.timezone = \"Europe/Berlin\"" >> /usr/local/etc/php/conf.d/timezone.ini && \
echo 'memory_limit = 2G' >> /usr/local/etc/php/conf.d/max_memory.ini
RUN apt-get update && \
  apt-get install -y \
    git \
    curl libcurl3-dev \
    mariadb-client \
    libpng-dev libwebp-dev libjpeg62-turbo-dev libfreetype6-dev libpng-dev \
    libxpm-dev \
    zip libzip-dev \
    gnupg2 \
    pcregrep \
    procps \
    imagemagick libmagickwand-dev \
    sudo && \
  docker-php-ext-configure curl && \
  docker-php-ext-install mysqli curl exif && \
  docker-php-ext-configure zip && \
  docker-php-ext-install zip && \
  docker-php-ext-configure gd --with-webp --with-jpeg --with-xpm --with-freetype && \
  docker-php-ext-install gd && \
  mkdir -p /usr/src/php/ext/imagick && pecl install imagick && docker-php-ext-enable imagick && \
  docker-php-ext-install pdo pdo_mysql && \
  docker-php-ext-install pcntl && \
  pecl install swoole && docker-php-ext-enable swoole

ADD imagick-policy.xml /etc/ImageMagick-6/policy.xml

ENV PHPREDIS_VERSION 5.3.7
RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

# The octance watcher requires node
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash && \
    apt-get install nodejs -yq && \
    apt-get clean -y

RUN pecl install xdebug && \
  docker-php-ext-enable xdebug && \
#  echo 'zend_extension = /usr/local/lib/php/extensions/no-debug-non-zts-20190902/xdebug.so' >> /usr/local/etc/php/php.ini && \
  touch /usr/local/etc/php/conf.d/xdebug.ini; \
  echo xdebug.mode=debug >> /usr/local/etc/php/conf.d/xdebug.ini; \
  echo xdebug.discover_client_host=true >> /usr/local/etc/php/conf.d/xdebug.ini

ENV PHPREDIS_VERSION 5.3.7
RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

WORKDIR /var/www

ADD setup.sh /usr/local/bin/setup
ADD run-dev.sh /run.sh

CMD /run.sh

